# Site settings
title: Samantha Beedie
email: info@samanthabeedie.com
url: https://www.samanthabeedie.com
description: "Artist and tattooist in the heart of Manchester city centre."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-bg: '#000000'
  links: '#219ab3'
  text: '#ffffff'

# Footer settings
footer: Samantha Beedie

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/samantha_beedie/

# Build settings
markdown: kramdown
permalink: pretty
