# Site settings
title: Samantha Beedie
email: info@samanthabeedie.com
formspree_token: xdaoazbm # Either form token or email address 
url: https://www.samanthabeedie.com
description: "Tattoo artist and illustrator in the heart of Manchester city centre."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-bg: '#000000'
  links: '#E69500'
  text: '#ffffff'

# Footer settings
footer: Samantha Beedie

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/samantha_beedie/

# Build settings
markdown: kramdown
permalink: pretty
